# Generated by Django 2.0.2 on 2018-03-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_auto_20180323_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useridname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='modell',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modell',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modell',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modell',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermentions',
            name='tweetid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Modell'),
        ),
    ]
