# Generated by Django 2.0.2 on 2018-03-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_auto_20180323_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modell',
            name='location',
        ),
        migrations.AlterField(
            model_name='modell',
            name='status',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='usermentions',
            name='tweetid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Modell'),
        ),
    ]
