# Generated by Django 2.0.2 on 2018-03-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_auto_20180323_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('tweetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Modell')),
            ],
        ),
        migrations.AlterField(
            model_name='usermentions',
            name='tweetid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Modell'),
        ),
    ]
