# Generated by Django 2.0.2 on 2018-03-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_auto_20180323_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='modell',
            name='location',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hashtags',
            name='tweetid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Modell'),
        ),
        migrations.AlterField(
            model_name='usermentions',
            name='tweetid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Modell'),
        ),
    ]
