# Generated by Django 2.0.2 on 2018-03-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0008_auto_20180325_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermentions',
            old_name='userm',
            new_name='tweetid',
        ),
        migrations.AlterField(
            model_name='hashtags',
            name='tweetidd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Modell'),
        ),
        migrations.AlterField(
            model_name='usermentions',
            name='tweetid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Modell'),
        ),
    ]
