# Generated by Django 2.0.2 on 2018-03-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0009_auto_20180325_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermentions',
            old_name='tweetid',
            new_name='userm',
        ),
        migrations.AlterField(
            model_name='hashtags',
            name='tweetidd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Modell'),
        ),
        migrations.AlterField(
            model_name='usermentions',
            name='userm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Modell'),
        ),
    ]
